#!/bin/bash
# Initializes and clones git repos needed for FW development

set -e

GERRIT="gerrit.lsdev.sil.org"
GERRITPORT=59418

# In Calgary use repos on git directly, otherwise use repos on github
# REVIEW: it might be better to redirect in the config file (see git-fetch(1)), especially if
# we use submodules or other files that hardcode the URI.
#if [ "$(dnsdomainname 2>/dev/null)" == "wycliffe.ca" ]; then
	REPOURI="git://gerrit.lsdev.sil.org"
#else
#	REPOURI="git://github.com/sillsdev"
#fi

# Version of the alias section in the config file. Increment the number each time you make some
# changes to setting the alias/guitool section below so that the config gets updated when this
# script is run.
THISALIASVERSION=2

# Get the directory of the fwmeta repo
getfwmetadir()
{
	local dir olddir curdir
	curdir=$(pwd)
	dir=$curdir

	while true; do
		cd $dir
		dir=$(git rev-parse --show-toplevel 2> /dev/null)
		if [ -z $dir ]; then
			echo "$curdir"
			return
		fi
		cd $dir
		if [ -d fwmeta ] && git config --file .git/config --get fwinit.initialized >/dev/null; then
			echo "$dir"
			return
		else
			olddir="$dir"
			dir=$(dirname "$dir")
			if [ "$olddir" == "$dir" ]; then
				echo "$curdir"
				return
			fi
		fi
	done
}

initrepo()
{
	repo=$1
	loc=$2
	basedir=$3

	echo
	echo "${_bold}Initializing project $repo${_normal}"

	cwd=$(pwd)
	mkdir -p "$loc"
	cd "$loc"
	git init .

	if [ "$reset" == "1" ]; then
		git config --unset fwinit.initialized
		git config --unset fwinit.aliasversion
	fi

	# Initialize origin
	if ! git remote | grep -q origin; then
		git remote add origin "$REPOURI/$repo.git"
	fi

	# setup push URL
	if ! git config --get-all remote.origin.pushurl | grep -q "ssh://$gerritusername@$GERRIT:$GERRITPORT/$repo.git"; then
		git remote set-url --add --push origin "ssh://$gerritusername@$GERRIT:$GERRITPORT/$repo.git"
	fi

	# Remove all fetch statements for origin so that we can add them again
	git config --unset-all remote.origin.fetch

	# update settings for notes
	git config notes.rewrite.amend true
	git config notes.rewrite.rebase true
	git config notes.rewriteRef "refs/notes/*"
	git config notes.displayRef "refs/notes/*"
	if ! git config --get-all remote.origin.fetch | grep -q notes; then
		git config --add remote.origin.fetch "+refs/notes/*:refs/notes/*"
	fi

	# fetch branches and setup tracking branch
	git remote set-branches --add origin $branchlist
	git fetch origin

	# we need the master and develop branches so that we can successfully initialize git-flow
	if ! git branch | grep -q master; then
		git checkout -q master
	fi
	if ! git branch | grep -q develop; then
		git checkout -q develop
	fi

	# install hook
	if [ ! -f .git/hooks/commit-msg ]; then
		echo "Getting commit hook:"
		if [ -z "$basedir" ]; then
			scp -p -P $GERRITPORT "$gerritusername@$GERRIT:hooks/commit-msg" .git/hooks
		else
			cp "$basedir/.git/hooks/commit-msg" .git/hooks/
		fi
	fi

	# Initialize git flow
	if ! git config --get gitflow.branch.master &>/dev/null; then
		git flow init -d
	fi

	if [ "$(git config --get fwinit.aliasversion)" != "$THISALIASVERSION" ]; then
		# adding some alias
		echo "Adding alias:"
		if ! git config --get fwinit.initialized &>/dev/null; then
			if [ "$(uname)" == "Linux" ]; then
				# there's some conflict here. When we use git from the command line
				# we don't want gedit here, but when we use git-gui we can't use vi.
				# So we set it to gedit for now; user might have to adjust later.
				git config core.editor "gedit -w"
				git config gui.editor "gedit -w"
			else
				git config core.editor "$(dirname $0)/winedit.sh"
			fi
			git config merge.tool "$mergetool"
			git config diff.guitool "$mergetool"
			git config fwinit.initialized 1
		fi
		if [ "$(git config --get fwinit.aliasversion || echo -1)" -lt "2" ]; then
			# Clean up old obsolete entries
			git config --remove-section "guitool.Bypass Code Review" 2> /dev/null || true
			git config --remove-section "guitool.Feature/Start" 2> /dev/null || true
			git config --remove-section "guitool.Feature/Submit for Code Review" 2> /dev/null || true
			git config --remove-section "guitool.Feature/Finish" 2> /dev/null || true
			git config --remove-section "guitool.Feature/Publish" 2> /dev/null || true
			git config --remove-section "guitool.Feature/Track" 2> /dev/null || true
			git config --remove-section "guitool.Release/Start" 2> /dev/null || true
			git config --remove-section "guitool.Release/Submit for Code Review" 2> /dev/null || true
			git config --remove-section "guitool.Release/Finish" 2> /dev/null || true
			git config --remove-section "guitool.Release/Publish" 2> /dev/null || true
			git config --remove-section "guitool.Release/Track" 2> /dev/null || true
			git config --remove-section "guitool.Hotfix/Start" 2> /dev/null || true
			git config --remove-section "guitool.Hotfix/Submit for Code Review" 2> /dev/null || true
			git config --remove-section "guitool.Hotfix/Finish" 2> /dev/null || true
			git config --remove-section "guitool.Support/Start" 2> /dev/null || true
			git config --remove-section "guitool.Support/Submit for Code Review" 2> /dev/null || true
			git config --remove-section "guitool.Support/Finish" 2> /dev/null || true
			git config --remove-section "guitool. Visual Diff" 2> /dev/null || true
		fi

		sedReplace="$(dirname "$0")"
		sedReplace=${sedReplace//\//\\\/} # replace all / with \/
		git config alias.featfin '!sh -c "SEDREPLACE/featfin.sh \$1" -'
		git config alias.review '!sh -c "SEDREPLACE/review.sh \$1 \$2" -'
		git config alias.release '!sh -c "SEDREPLACE/relfin.sh \$1" -'
		git config alias.hotfin '!sh -c "SEDREPLACE/hotfin.sh \$1" -'
		git config alias.supfin '!sh -c "SEDREPLACE/supfin.sh \$1" -'
		git config alias.mergepush '!sh -c "git mergetool -y && git commit && git push origin && git push origin --tags" -'
		# do this last so that we can replace multiple entries at once
		sed "s/SEDREPLACE/$sedReplace/g" .git/config 2>&1 > .git/config2
		mv .git/config2 .git/config

		git config guitool.0_Feature/0_Start.cmd 'git flow feature start $ARGS'
		git config guitool.0_Feature/0_Start.argprompt "Feature name (JIRA number)"
		git config "guitool.0_Feature/1_Submit for Code Review.cmd" 'git push origin HEAD:refs/for/develop/$CUR_BRANCH'
		git config guitool.0_Feature/2_Finish.cmd 'git featfin ${CUR_BRANCH#*/}'
		git config guitool.0_Feature/Publish.cmd 'git flow feature publish ${CUR_BRANCH#*/}'
		git config guitool.0_Feature/Track.cmd 'git flow feature track $ARGS'
		git config guitool.0_Feature/Track.argprompt "Name of the feature"

		git config guitool.1_Release/0_Start.cmd 'git flow release start $ARGS'
		git config guitool.1_Release/0_Start.argprompt "Name of the release"
		git config "guitool.1_Release/1_Submit for Code Review.cmd" 'git push origin HEAD:refs/for/$CUR_BRANCH'
		git config guitool.1_Release/2_Finish.cmd 'git release ${CUR_BRANCH#*/}'
		git config guitool.1_Release/Publish.cmd 'git flow release publish ${CUR_BRANCH#*/}'
		git config guitool.1_Release/Track.cmd 'git flow release track $ARGS'
		git config guitool.1_Release/Track.argprompt "Name of the release"

		git config guitool.2_Hotfix/0_Start.cmd 'git flow hotfix start $ARGS'
		git config guitool.2_Hotfix/0_Start.argprompt "Name of the fixed version"
		git config "guitool.2_Hotfix/1_Submit for Code Review.cmd" 'git push origin HEAD:refs/for/master/$CUR_BRANCH'
		git config guitool.2_Hotfix/2_Finish.cmd 'git hotfin ${CUR_BRANCH#*/}'

		git config guitool.3_Support/0_Start.cmd 'git flow support start $ARGS'
		git config guitool.3_Support/0_Start.argprompt "Name of the support branch and tag it is based on (e.g. '1.0 1.0')"
		git config "guitool.3_Support/1_Submit for Code Review.cmd" 'git push origin HEAD:refs/for/$CUR_BRANCH'
		git config guitool.3_Support/2_Finish.cmd 'git supfin $ARGS'
		git config guitool.3_Support/2_Finish.argprompt "Name of the new version"

		git config "guitool.Advanced/Bypass Code Review.cmd" 'git push origin $CUR_BRANCH'
		git config "guitool.Interactive Rebase.cmd" 'git rebase -i $REVISION'
		git config "guitool.Interactive Rebase.revprompt" yes
		git config "guitool.Interactive Rebase (Continue).cmd" 'git rebase --continue'
		git config "guitool.Interactive Rebase (Abort).cmd" 'git rebase --abort'
		git config "guitool.Visual Diff.cmd" 'git difftool -y $FILENAME'
		git config "guitool.Visual Diff.needsfile" yes
		git config "guitool.Visual Diff.noconsole" yes
		git config "guitool.Visual Merge.cmd" 'git mergetool -y'
		git config "guitool.Visual Merge.noconsole" yes
		git config "guitool.Visual Merge and Push.cmd" 'git mergepush'
		git config "guitool.Visual Merge.noconsole" yes

		git config fwinit.aliasversion "$THISALIASVERSION"
	fi
	cd "$cwd"
}


basedir=$(getfwmetadir)
cd "$basedir"
if [ "$1" != "--recursive" ]; then
	if [ -d ".git" ] && git remote | grep -q origin ; then
		# fwmeta repo exists. Let's see if we're on a branch that has a tracking-branch.
		# If we are then update the repo, otherwise assume we're in the middle of
		# developing some changes, so we leave it alone.
		if git rev-parse --abbrev-ref --symbolic-full-name @{u} &> /dev/null; then
			git pull --rebase origin
		fi
	else
		# fwmeta repo doesn't exist yet. Clone it.
		git clone git://gerrit.lsdev.sil.org/fwmeta.git
		basedir=$basedir/fwmeta
	fi
	# recursive call so that we run with the latest version
	$basedir/fwmeta/initrepo --recursive $*
	exit
fi
shift
reset=0
[ "$1" == "--reset" ] && reset=1

. "$basedir/fwmeta/functions.sh"
. "$basedir/fwmeta/repodefs.sh"

# Sanity checks
if ! git flow version &>/dev/null; then
	echo "Can't find git-flow. Please install."
	exit 1
fi

gerritusername=$(git config --get fwinit.gerrituser) || true
username=$(git config --get user.name) || true
useremail=$(git config --get user.email) || true
mergetool=$(git config --get merge.tool) || true
mergetool=${mergetool:-p4merge}

savevalues=false

# Query user for variables
if [ -z "$username" ]; then
	username="${username:-$(fullname)}"
	username=$(readdefault "Full name" "$username")
	savevalues=true
fi
# Convert username to lowercase and replace spaces with underscore
# Note: we can't use ${username,,} to convert to lowercase because that's a bash 4.0 feature
# and so doesn't work on Windows
defname="$(echo ${username// /_} | tr '[A-Z]' '[a-z]')"
if [ -z "$useremail" ]; then
	useremail="${useremail:-$defname@sil.org}"
	useremail=$(readdefault "Email address" "$useremail")
	savevalues=true
fi
if [ -z "$gerritusername" ]; then
	gerritusername="${gerritusername:-$defname}"
	gerritusername=$(readdefault "Gerrit username" "${gerritusername}")
	savevalues=true
fi

if "$savevalues"; then
	# Store variables for later use
	git config --global user.name "$username"
	git config --global user.email "$useremail"
	git config --global fwinit.gerrituser "$gerritusername"
fi

if [ -z "$mergetool" ]; then
	mergetool=$(readdefault "Merge tool [p4merge, kdiff3]" "$mergetool")
fi

repolist=$(git config --get fwinit.repolist) || true
[ "$reset" == 1 ] && repolist=""
if [ -z "$repolist" ]; then
	echo "Available repos: $(getAllReposForPlatform)"
	defaultlist="FieldWorks FwSampleProjects"
	if [ "$(platform)" == "Linux" ]; then
		defaultlist+=" mono mono-basic gtk-sharp libgdiplus"
	fi

	repolist=$(readdefault "Repos to clone" "$defaultlist")
	git config fwinit.repolist "$repolist"
fi
branchlist=$(git config --get fwinit.branchlist) || true
[ "$reset" == 1 ] && branchlist=""
if [ -z "$branchlist" ]; then
	branchlist=$(readdefault "Branches to fetch" "master develop")
	git config fwinit.branchlist "$branchlist"
fi

initrepo fwmeta .

for repo in $repolist; do
	initrepo "$repo" "$(getDirForRepo $repo)" "$basedir"
done
