#!/bin/bash
# Show the status for all repos defined in repodefs.sh

NOCOLORS=$1

FWMETAREPO=fwmeta
TOOLSDIR=fwmeta

# need to unset GIT_WORK_TREE and GIT_DIR when running from git gui
unset GIT_WORK_TREE
unset GIT_DIR

olddir="$(pwd)"
cd "$(dirname "$0")"
basedir=$(git rev-parse --show-toplevel)
cd "$olddir"

. "$basedir/$TOOLSDIR/functions.sh"
. "$basedir/$TOOLSDIR/repodefs.sh"

if [ ! -z $NOCOLORS ] ; then
	_nl="\n"
fi

fwmetadir="$(getfwmetadir)"

# show the status for repo $1 in directory $2
showstatus()
{
	cd "$fwmetadir/$2"
	echo -e "$(printf "${_nl}${_bold}%-47s %s${_normal}" "project $1/" "branch $(currentBranch)")"
	echo "Location: $fwmetadir/$2"
	git status -s
	cd "$fwmetadir"
}

showstatus "$TOOLSDIR" "."

for repo in $(getAllRepos); do
	dir="$(getDirForRepo $repo)"
	if [ -d "$dir/.git" ]; then
		showstatus "$repo" "$dir"
	fi
done
